# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '19 16 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-pr-message: 'Stale pull request message'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
    - name: Setup Go environment
      uses: actions/setup-go@v3.2.1
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.18
        # Path to the go.mod file.
        #go-version-file: # optional
        # Set this option to true if you want the action to always check for the latest available version that satisfies the version spec
        #check-latest: # optional
        # Used to pull node distributions from go-versions.  Since there's a default, this is typically not supplied by the user.
        #token: # optional, default is ${{ github.token }}
        # Used to specify whether caching is needed. Set to true, if you'd like to enable caching.
        #cache: # optional
        # Used to specify the path to a dependency file - go.sum
        #cache-dependency-path: # optional
